-- =============================================================================
-- MySolutionHub — Master Database Schema
-- Database: mysolutionhub_master
-- Provider: PostgreSQL 16+
-- Descrizione: Tabelle di controllo multi-tenant (Tenants, Connections,
--              Features, Settings, MigrationLogs, AuditLogs)
-- =============================================================================

-- Tabella di tracking delle migrazioni EF Core (creata automaticamente,
-- inclusa qui per documentazione e setup manuale)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"  varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- =============================================================================
-- TENANTS
-- Anagrafica dei tenant registrati sulla piattaforma
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Tenants" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"  text    NOT NULL,           -- Identificatore univoco logico (es. "acme-corp")
    "Subdomain" text    NOT NULL,           -- Sottodominio (es. "acme")
    "Name"      text    NOT NULL,           -- Nome visualizzato
    "IsActive"  boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "AK_Tenants_TenantId"
    ON "Tenants" ("TenantId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tenants_Subdomain"
    ON "Tenants" ("Subdomain");

-- =============================================================================
-- TENANT CONNECTIONS
-- Connection string cifrata per ogni tenant (una per tenant)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "TenantConnections" (
    "Id"                         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"                   text    NOT NULL,
    "ConnectionStringEncrypted"  text    NOT NULL,   -- AES-256 cifrato
    "DbVersion"                  text    NOT NULL,
    "Region"                     text    NOT NULL,   -- Es. "eu-west"
    "UpdatedAt"                  timestamp NOT NULL,
    CONSTRAINT "FK_TenantConnections_Tenants"
        FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("TenantId")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TenantConnections_TenantId"
    ON "TenantConnections" ("TenantId");

-- =============================================================================
-- TENANT FEATURES
-- Feature flag per tenant (es. "social:feed", "social:chat")
-- =============================================================================
CREATE TABLE IF NOT EXISTS "TenantFeatures" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"  text    NOT NULL,
    "FeatureKey" text   NOT NULL,           -- Es. "social:feed"
    "IsEnabled" boolean NOT NULL DEFAULT false,
    "Config"    text    NULL,               -- JSON opzionale con parametri feature
    CONSTRAINT "FK_TenantFeatures_Tenants"
        FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("TenantId")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TenantFeatures_TenantId"
    ON "TenantFeatures" ("TenantId");

-- =============================================================================
-- TENANT SETTINGS
-- Chiave-valore configurabili per tenant
-- =============================================================================
CREATE TABLE IF NOT EXISTS "TenantSettings" (
    "Id"        integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"  text         NOT NULL,
    "Key"       varchar(200) NOT NULL,
    "Value"     varchar(2000) NOT NULL,
    "UpdatedAt" timestamp    NOT NULL,
    CONSTRAINT "FK_TenantSettings_Tenants"
        FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("TenantId")
        ON DELETE CASCADE
);

-- Chiave composta univoca: un solo valore per (tenant, chiave)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TenantSettings_TenantId_Key"
    ON "TenantSettings" ("TenantId", "Key");

-- =============================================================================
-- TENANT MIGRATION LOGS
-- Traccia l'esecuzione delle migrazioni EF Core su ogni DB tenant
-- Status: 0=Pending, 1=Completed, 2=Failed
-- =============================================================================
CREATE TABLE IF NOT EXISTS "TenantMigrationLogs" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"     text    NOT NULL,
    "MigrationId"  text    NOT NULL,
    "AppliedAt"    timestamp NOT NULL,
    "Status"       integer NOT NULL DEFAULT 0,  -- Enum: 0=Pending,1=Completed,2=Failed
    "ErrorMessage" text    NULL,
    CONSTRAINT "FK_TenantMigrationLogs_Tenants"
        FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("TenantId")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TenantMigrationLogs_TenantId"
    ON "TenantMigrationLogs" ("TenantId");

-- =============================================================================
-- AUDIT LOGS
-- Log immutabile di tutte le azioni rilevanti sulla piattaforma
-- =============================================================================
CREATE TABLE IF NOT EXISTS "AuditLogs" (
    "Id"         integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId"   text         NULL,                 -- NULL per azioni globali (es. provisioning)
    "ActorId"    varchar(100) NOT NULL,             -- Id utente o "system"
    "ActorName"  varchar(256) NOT NULL,
    "Action"     varchar(100) NOT NULL,             -- Es. "user:login", "tenant:provision"
    "EntityType" varchar(100) NULL,
    "EntityId"   varchar(100) NULL,
    "Changes"    varchar(4000) NULL,                -- JSON diff opzionale
    "IpAddress"  varchar(45)  NULL,                 -- Supporta IPv6
    "Timestamp"  timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_AuditLogs_TenantId"
    ON "AuditLogs" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp"
    ON "AuditLogs" ("Timestamp");

-- =============================================================================
-- NOTE
-- • Le tabelle Hangfire (schema "hangfire.*") sono create automaticamente
--   dal package Hangfire.PostgreSql all'avvio dell'applicazione.
-- • Tutte le FK verso Tenants usano ON DELETE CASCADE.
-- • L'encryption dei ConnectionString usa AES-256 con IV casuale per record.
-- =============================================================================
