-- =============================================================================
-- MySolutionHub — Tenant Database Schema
-- Database: mysolutionhub_<tenant_id>   (uno per tenant)
-- Provider: PostgreSQL 16+
-- Descrizione: Tabelle per ogni singolo tenant — Identity, Social Layer,
--              Chat, Notifiche, Refresh Token
-- =============================================================================

-- Tabella di tracking delle migrazioni EF Core
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    varchar(150) NOT NULL,
    "ProductVersion" varchar(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- =============================================================================
-- IDENTITY — ASP.NET Core Identity (IdentityUser<int>)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id"               integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"             varchar(256) NULL,
    "NormalizedName"   varchar(256) NULL,
    "ConcurrencyStamp" text         NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON "Roles" ("NormalizedName")
    WHERE "NormalizedName" IS NOT NULL;

-- Users estende IdentityUser<int> con campi custom
CREATE TABLE IF NOT EXISTS "Users" (
    -- Campi IdentityUser<int>
    "Id"                  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName"            varchar(256) NULL,
    "NormalizedUserName"  varchar(256) NULL,
    "Email"               varchar(256) NULL,
    "NormalizedEmail"     varchar(256) NULL,
    "EmailConfirmed"      boolean      NOT NULL DEFAULT false,
    "PasswordHash"        text         NULL,
    "SecurityStamp"       text         NULL,
    "ConcurrencyStamp"    text         NULL,
    "PhoneNumber"         text         NULL,
    "PhoneNumberConfirmed" boolean     NOT NULL DEFAULT false,
    "TwoFactorEnabled"    boolean      NOT NULL DEFAULT false,
    "LockoutEnd"          timestamp with time zone NULL,
    "LockoutEnabled"      boolean      NOT NULL DEFAULT false,
    "AccessFailedCount"   integer      NOT NULL DEFAULT 0,
    -- Campi custom ApplicationUser
    "FirstName"           varchar(100) NULL,
    "LastName"            varchar(100) NULL,
    "UserType"            integer      NOT NULL DEFAULT 1,  -- 0=Internal, 1=External
    "AvatarUrl"           text         NULL,
    "IsActive"            boolean      NOT NULL DEFAULT true,
    "IsDeleted"           boolean      NOT NULL DEFAULT false,  -- Soft delete
    "LastLoginAt"         timestamp    NULL,
    "CreatedAt"           timestamp    NOT NULL DEFAULT now(),
    "UpdatedAt"           timestamp    NULL
);

-- Query filter su IsDeleted applicato da EF Core
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"
    ON "Users" ("Email")
    WHERE "Email" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_UserName"
    ON "Users" ("UserName")
    WHERE "UserName" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON "Users" ("NormalizedEmail");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON "Users" ("NormalizedUserName")
    WHERE "NormalizedUserName" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "UserClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     integer NOT NULL,
    "ClaimType"  text    NULL,
    "ClaimValue" text    NULL,
    CONSTRAINT "FK_UserClaims_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId"
    ON "UserClaims" ("UserId");

CREATE TABLE IF NOT EXISTS "UserLogins" (
    "LoginProvider"       text    NOT NULL,
    "ProviderKey"         text    NOT NULL,
    "ProviderDisplayName" text    NULL,
    "UserId"              integer NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId"
    ON "UserLogins" ("UserId");

CREATE TABLE IF NOT EXISTS "UserTokens" (
    "UserId"        integer NOT NULL,
    "LoginProvider" text    NOT NULL,
    "Name"          text    NOT NULL,
    "Value"         text    NULL,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId"  integer NOT NULL,
    "RoleId"  integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId"
    ON "UserRoles" ("RoleId");

CREATE TABLE IF NOT EXISTS "RoleClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId"     integer NOT NULL,
    "ClaimType"  text    NULL,
    "ClaimValue" text    NULL,
    CONSTRAINT "FK_RoleClaims_Roles"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId"
    ON "RoleClaims" ("RoleId");

-- =============================================================================
-- REFRESH TOKENS
-- Gestione dei refresh token JWT con rotation e revocation
-- =============================================================================
CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id"              integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          integer      NOT NULL,
    "Token"           varchar(500) NOT NULL,
    "ExpiresAt"       timestamp    NOT NULL,
    "IsRevoked"       boolean      NOT NULL DEFAULT false,
    "ReplacedByToken" varchar(500) NULL,    -- Token successivo nella catena di rotation
    "CreatedAt"       timestamp    NOT NULL DEFAULT now(),
    "UpdatedAt"       timestamp    NULL,
    "IsDeleted"       boolean      NOT NULL DEFAULT false,
    CONSTRAINT "FK_RefreshTokens_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_Token"
    ON "RefreshTokens" ("Token");

CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId"
    ON "RefreshTokens" ("UserId");

-- =============================================================================
-- SOCIAL LAYER — Activity Feed
-- =============================================================================

-- Evento pubblicato nel feed (post, commento, follow, ecc.)
CREATE TABLE IF NOT EXISTS "ActivityEvents" (
    "Id"          integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      integer  NOT NULL,
    "EventType"   varchar(100) NOT NULL,   -- Es. "post:create", "user:follow"
    "EntityId"    text     NULL,           -- Id dell'entità correlata
    "EntityType"  text     NULL,           -- Tipo dell'entità correlata
    "Payload"     text     NULL,           -- JSON con dati aggiuntivi
    "IsPublic"    boolean  NOT NULL DEFAULT true,
    "CreatedAt"   timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"   timestamp NULL,
    "IsDeleted"   boolean  NOT NULL DEFAULT false,
    CONSTRAINT "FK_ActivityEvents_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ActivityEvents_UserId_CreatedAt"
    ON "ActivityEvents" ("UserId", "CreatedAt" DESC);

-- Reazioni agli eventi del feed (like, ecc.) — una per utente per evento
CREATE TABLE IF NOT EXISTS "ActivityReactions" (
    "Id"           integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId"      integer  NOT NULL,
    "UserId"       integer  NOT NULL,
    "ReactionType" text     NOT NULL DEFAULT 'like',
    "CreatedAt"    timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"    timestamp NULL,
    "IsDeleted"    boolean  NOT NULL DEFAULT false,
    CONSTRAINT "FK_ActivityReactions_Events"
        FOREIGN KEY ("EventId") REFERENCES "ActivityEvents" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_ActivityReactions_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

-- Un utente può reagire al massimo una volta per evento
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ActivityReactions_EventId_UserId"
    ON "ActivityReactions" ("EventId", "UserId");

-- Relazioni follower/followed tra utenti
CREATE TABLE IF NOT EXISTS "UserFollows" (
    "Id"         integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FollowerId" integer  NOT NULL,
    "FollowedId" integer  NOT NULL,
    "IsActive"   boolean  NOT NULL DEFAULT true,
    "CreatedAt"  timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"  timestamp NULL,
    "IsDeleted"  boolean  NOT NULL DEFAULT false,
    CONSTRAINT "FK_UserFollows_Follower"
        FOREIGN KEY ("FollowerId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_UserFollows_Followed"
        FOREIGN KEY ("FollowedId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "CK_UserFollows_NoSelfFollow"
        CHECK ("FollowerId" <> "FollowedId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserFollows_FollowerId_FollowedId"
    ON "UserFollows" ("FollowerId", "FollowedId");

-- =============================================================================
-- CHAT
-- =============================================================================

-- Conversazione (diretta 1:1 o gruppo)
CREATE TABLE IF NOT EXISTS "ChatConversations" (
    "Id"            integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"         text     NULL,              -- NULL per chat 1:1 (titolo = username altro utente)
    "IsGroup"       boolean  NOT NULL DEFAULT false,
    "LastMessageAt" timestamp NULL,
    "CreatedAt"     timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"     timestamp NULL,
    "IsDeleted"     boolean  NOT NULL DEFAULT false
);

-- Partecipanti a una conversazione
-- Role: 0=Member, 1=Admin
CREATE TABLE IF NOT EXISTS "ChatParticipants" (
    "Id"             integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConversationId" integer  NOT NULL,
    "UserId"         integer  NOT NULL,
    "Role"           integer  NOT NULL DEFAULT 0,  -- 0=Member, 1=Admin
    "IsActive"       boolean  NOT NULL DEFAULT true,
    "LeftAt"         timestamp NULL,
    "CreatedAt"      timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"      timestamp NULL,
    "IsDeleted"      boolean  NOT NULL DEFAULT false,
    CONSTRAINT "FK_ChatParticipants_Conversations"
        FOREIGN KEY ("ConversationId") REFERENCES "ChatConversations" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_ChatParticipants_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatParticipants_ConversationId_UserId"
    ON "ChatParticipants" ("ConversationId", "UserId");

-- Messaggi di una conversazione
CREATE TABLE IF NOT EXISTS "ChatMessages" (
    "Id"             integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConversationId" integer  NOT NULL,
    "SenderId"       integer  NOT NULL,
    "Body"           text     NOT NULL,
    "AttachmentUrl"  text     NULL,
    "SentAt"         timestamp NOT NULL DEFAULT now(),
    "CreatedAt"      timestamp NOT NULL DEFAULT now(),
    "UpdatedAt"      timestamp NULL,
    "IsDeleted"      boolean  NOT NULL DEFAULT false,
    CONSTRAINT "FK_ChatMessages_Conversations"
        FOREIGN KEY ("ConversationId") REFERENCES "ChatConversations" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_Users"
        FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_SentAt"
    ON "ChatMessages" ("ConversationId", "SentAt");

-- Tracciamento messaggi letti per utente
CREATE TABLE IF NOT EXISTS "MessageReadStatuses" (
    "Id"        integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MessageId" integer  NOT NULL,
    "UserId"    integer  NOT NULL,
    "ReadAt"    timestamp NOT NULL DEFAULT now(),
    CONSTRAINT "FK_MessageReadStatuses_Messages"
        FOREIGN KEY ("MessageId") REFERENCES "ChatMessages" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_MessageReadStatuses_Users"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MessageReadStatuses_MessageId_UserId"
    ON "MessageReadStatuses" ("MessageId", "UserId");

-- =============================================================================
-- NOTIFICATIONS
-- Notifiche push in-app per ogni utente
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id"         integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     integer      NOT NULL,          -- Destinatario
    "SenderId"   integer      NULL,              -- Mittente (opzionale)
    "Type"       varchar(100) NOT NULL,          -- Es. "follow", "reaction", "message"
    "Title"      varchar(200) NOT NULL,
    "Message"    text         NOT NULL,
    "EntityId"   text         NULL,
    "EntityType" text         NULL,
    "IsRead"     boolean      NOT NULL DEFAULT false,
    "ReadAt"     timestamp    NULL,
    "CreatedAt"  timestamp    NOT NULL DEFAULT now(),
    "UpdatedAt"  timestamp    NULL,
    "IsDeleted"  boolean      NOT NULL DEFAULT false,
    CONSTRAINT "FK_Notifications_Users_Recipient"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_Notifications_Users_Sender"
        FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id")
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId_IsRead"
    ON "Notifications" ("UserId", "IsRead");

-- =============================================================================
-- SEED DATA — Ruoli base (eseguire dopo la creazione delle tabelle)
-- =============================================================================

INSERT INTO "Roles" ("Name", "NormalizedName", "ConcurrencyStamp")
SELECT 'Admin',    'ADMIN',    gen_random_uuid()::text WHERE NOT EXISTS (SELECT 1 FROM "Roles" WHERE "NormalizedName" = 'ADMIN');

INSERT INTO "Roles" ("Name", "NormalizedName", "ConcurrencyStamp")
SELECT 'Internal', 'INTERNAL', gen_random_uuid()::text WHERE NOT EXISTS (SELECT 1 FROM "Roles" WHERE "NormalizedName" = 'INTERNAL');

INSERT INTO "Roles" ("Name", "NormalizedName", "ConcurrencyStamp")
SELECT 'External', 'EXTERNAL', gen_random_uuid()::text WHERE NOT EXISTS (SELECT 1 FROM "Roles" WHERE "NormalizedName" = 'EXTERNAL');

-- =============================================================================
-- NOTE
-- • IsDeleted: soft delete gestito da EF Core query filter (IsDeleted = false).
--   Le righe cancellate rimangono fisicamente nel DB.
-- • Tutti i timestamp sono in UTC (l'app usa DateTime.UtcNow).
-- • Le tabelle Hangfire NON sono incluse: create automaticamente da
--   Hangfire.PostgreSql nello schema "hangfire".
-- • I check constraint CK_UserFollows_NoSelfFollow non è presente nelle
--   migrazioni EF ma è consigliato a livello DB.
-- =============================================================================
